name: Java CI

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Cardea
          path: build/libs

  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - name: Build artifact
        run: ./gradlew clean build
      - name: Export LATEST_TAG
        run: |
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Upload Release Artifact
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run:
          gh release upload ${{ env.LATEST_TAG }} build/libs/*.jar
      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 3C31Qs54
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            paper
          game-versions: |-
            1.21.8
            1.21.7
          files: build/libs/Cardea-${{ github.event.release.tag_name }}.jar
